FROM jupyter/pyspark-notebook:spark-3.2.1

COPY ./jars/ /usr/local/spark/jars/
# RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.704/aws-java-sdk-bundle-1.11.704.jar --output /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.704.jar