version: "3"
services:
  mongodb:
    image : mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all"]
    container_name: mongodb
    volumes:
    - ./mongo/:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
    networks:
      - docker-stack 

networks:
  docker-stack: