version: '3'
services:
  notebook:
    image: jupyter/all-spark-notebook
    ports:
      - 8889:8888
      - 4041:4040
    environment:
      - PYSPARK_SUBMIT_ARGS=--packages com.amazonaws:aws-java-sdk-bundle:1.11.819,org.apache.hadoop:hadoop-aws:3.2.0 pyspark-shell
    volumes:
      - ./work:/home/jovyan/work

    networks:
      - docker-stack  

networks:
  docker-stack:  