---
version: '3'
# Example based on https://github.com/Stefen-Taime/docker-stack

services:
  postgres:
    container_name: ${CONTAINER_NAME}
    image: 'postgres:${PG_VER}'
    hostname: ${HOSTNAME}
    ports:
      - "5432:${PORT}"
    environment:
      TZ: ${TZ_SET}
      restart: always
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SRC_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}  
    #    PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./scripts:/scripts
    networks:
      - docker-stack
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: ${PORT}
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_SRC_PASSWORD}
      MB_DB_HOST: ${HOSTNAME}
    depends_on: 
      postgres:
        condition: service_healthy
    networks:
      - docker-stack    
      

  mysql:
    build:
      context: ./mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MY_DB_NAME}
      - MYSQL_USER=${MY_DB_USER}
      - MYSQL_PASSWORD=${MY_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MY_DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/data:/var/lib/mysql 
    networks:
      - docker-stack   


  adminer:
    image: adminer:latest
    ports:
    - 8085:8080/tcp
    deploy:
     restart_policy:
       condition: on-failure
    networks:
      - docker-stack  
   
    
networks:
  docker-stack: