version: '3'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: ${PORT}
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_SRC_PASSWORD}
      MB_DB_HOST: ${HOSTNAME}
    depends_on: 
      postgres:
    networks:
      - docker-stack
networks:
  docker-stack:          
