version: "3"
services:
  minio:
    hostname: minio
    image: 'minio/minio:RELEASE.2021-01-08T21-18-21Z'
    container_name: minio
    ports:
      - '9000:9000'
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ACCESS_KEY: ${ACCESS_KEY}
      MINIO_SECRET_KEY: ${SECRET_KEY}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - docker-stack

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - docker-stack  
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:${MINIO_PORT} ${ACCESS_KEY} ${SECRET_KEY};
      /usr/bin/mc mb myminio/${DATA_REPO_BUCKET_NAME};
      /usr/bin/mc policy set public myminio/${DATA_REPO_BUCKET_NAME};
      exit 0;
      "
networks:
  docker-stack: